name: psql-docker-build-release

on:
  release:
    types: [released, edited]

jobs:
  test:
    if: "!github.event.release.prerelease"

    runs-on: ubuntu-latest

    steps:
    - name: echo step
      run: echo "test is running running"

  otherJob:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
    - name: echo step
      run: echo "other ob is running!"
